sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
install:
  - npm install -g truffle
  - npm install
script:
  - npm run coverage
after_script:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
